sonar.projectKey=juice-shop
sonar.organization=juice-shop-agrandin
# Ces infos se trouvent sur la page d'accueil de ton projet SonarCloud
sonar.sources=lib,routes,data,models
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info